### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by Richard-Regan** [junpataleta/moodle-ubuntu#1]
Hi,

Is this still a preferred way to get a development environment?

As the chrome driver section, and the moodle-sdk sections both failed to install.

**Comment by junpataleta** [comment]
Hi, Richard!

Thanks for checking out my installation script! 

What Ubuntu version are you using? I tested the recent `main` branch of this script on Ubuntu 22.04, and the MDK installation works okay. However, I have not yet tested it on later versions of Ubuntu.

Regarding the Chromedriver setup, it needs to be updated to download the latest stable Chromedriver version based on their [JSON API endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints). I'll look into this when I find the time.

**Comment by junpataleta** [comment]
The Chromedriver setup has been fixed, and the MDK installation is now fixed on Ubuntu 24.04. 

There's an issue with the Oracle PHP driver installation on Ubuntu 24.04, which will show PHP warnings about missing oci8 drivers. For now, devs should disable the extension as a workaround using `sudo phpdismod oci8`. I'll look into it on a separate issue. 

In the meantime, I'm closing this. Cheers!
